#define os if
#define arall else
#define tra while
#define wneud do
#define dychwelyd return
#define gwagle void
#define cyf int
#define strw struct
#define torri break
#define parhewch continue
#define prif main
#define am for
#define brintf printf
